import type { Metadata } from "next";
import UserNavBar from "@/components/user/navbar/UserNavBar";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata: Metadata = {
  title: "FotoGifty",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function UserMainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute redirectTo="/login">
      <div>
        <div className=" flex w-full flex-row bg-background">
          <UserNavBar /> <main className=" w-full">{children}</main>
        </div>
      </div>
    </ProtectedRoute>
  );
}
