import type { Metadata } from "next";
import NavBar from "@/components/landing-page/navbar/NavBar";
import ProtectedRoute from "@/components/ProtectedRoute";
import { navbarLinks } from "@/interfaces/navbar";

export const metadata: Metadata = {
  title: "FotoGifty",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function UserMainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sections: navbarLinks[] = [
    { label: "Productos", href: "/user" },
    { label: "Mi Carrito", href: "/user/cart" },
    { label: "Mis Pedidos", href: "/user/backlog" },
  ];

  return (
    <ProtectedRoute redirectTo="/login">
      <div className="min-h-screen flex flex-col">
        <NavBar sections={sections} />
        <main className="flex-1 w-full">{children}</main>
      </div>
    </ProtectedRoute>
  );
}
