import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Poppins, Raleway } from "next/font/google";
import AuthProvider from "@/providers/AuthProvider";

export const metadata: Metadata = {
  title: "FotoGifty",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const viewport: Viewport = {
  viewportFit: "cover",
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${raleway.className} ${poppins.className}`}>
        <AuthProvider>
          <main className="w-full overflow-x-clip font-raleway">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
