import AdmiNavbar from "@/components/admin/AdmiNavbar";
import type { Metadata } from "next";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata: Metadata = {
  title: "FotoGifty",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function AdmiLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute allowedRoles={['admin', 'super_admin']} redirectTo="/login/admin">
      <div>
        <AdmiNavbar />
        <main className="w-full overflow-x-clip">{children}</main>
      </div>
    </ProtectedRoute>
  );
}
