import type { Metadata } from "next";
import ProtectedRoute from "@/components/ProtectedRoute";

export const metadata: Metadata = {
  title: "FotoGifty",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function UserLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProtectedRoute redirectTo="/login">
      <div className=" flex w-full bg-background overflow-x-clip">
        <main className="w-full font-raleway">{children}</main>
      </div>
    </ProtectedRoute>
  );
}
